#pragma once


#ifndef TLTEST_DEFAULT_H
#define TLTEST_DEFAULT_H


#ifndef TLTEST_DEFAULT_SEED
#   define TLTEST_DEFAULT_SEED                          0
#endif


#ifndef TLTEST_DEFAULT_CORE_COUNT
#   define TLTEST_DEFAULT_CORE_COUNT                    1
#endif

#ifndef TLTEST_DEFAULT_MASTER_COUNT_PER_CORE_TLC
#   define TLTEST_DEFAULT_MASTER_COUNT_PER_CORE_TLC     1
#endif

#ifndef TLTEST_DEFAULT_MASTER_COUNT_PER_CORE_TLUL
#   define TLTEST_DEFAULT_MASTER_COUNT_PER_CORE_TLUL    0
#endif


#endif // TLTEST_DEFAULT_H